### ISSUE TITLE
How to open this release?

### ISSUE THREAD

**Issue by StevenLi-phoenix** [myzhang1029/basic_kbdyi#1]
This release is kmp file and when I search how to open it I found this explain:
_What is a KMP file?
Course file used by the Mario Kart Wii, a Nintendo video game; contains course data divided into different sections, each describing different aspects of the course; includes start positions of racers, check points, camera positions, re-spawning positions, object positions, and other stage information._
But this is mentioned as an keyboard?

SO How can I open It?

**Comment by myzhang1029** [comment]
This keyboard is made to be used with [Keyman](https://keyman.com).
